### ISSUE TITLE
Add what people should look out for after gulp ran

### ISSUE THREAD

**Issue by avermeulen** [SteveBarnett/gulp-uncss-example#1]
What about adding this: Look at the css and see that `x` is no longer in the css...

**Comment by SteveBarnett** [comment]
@avermeulen good catch. Thanks!

**Comment by avermeulen** [comment]
What about changing this:

For the files included in this example, your trimmed CSS file in should look like this:

To something like:

A new `main.css` file will be created in the `./out` folder that will look like this:

// css here

Note that the unused css elements have been removed.

**Comment by SteveBarnett** [comment]
Mmm, good, me like. Have updated README.
